INSERT INTO public."NovaCidade"( "ID", nome, ativo, "createdAt", "updatedAt", "deletedAt", "estadoID") VALUES (1, 'Brasília', true, current_timestamp, current_timestamp, null, 7);
	
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (1  , 'Asa Norte', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (2  , 'Zona Cívico-Administrativa', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (3  , 'Asa Sul', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (4  , 'Vila da Telebrasília', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (5  , 'Setor Policial Sul', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (6  , 'Setores Complementares', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (7  , 'Setor Militar Urbano', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (8  , 'Zona Industrial', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (9  , 'Granja do Torto', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (10 , 'Cruzeiro Velho', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (11 , 'Cruzeiro Novo', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (12 , 'Área Octogonal', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (13 , 'Setor Sudoeste', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (14 , 'Setor Noroeste', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (15 , 'Vila Planalto', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (16 , 'Campus Universitário Darcy Ribeiro', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (17 , 'Guará II', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (18 , 'Guará I', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (19 , 'Quadras Econômicas Lúcio Costa (Guará)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (20 , 'Zona Industrial (Guará)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (21 , 'Setor Central (Vila Estrutural)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (22 , 'Setor Oeste (Vila Estrutural)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (23 , 'Setor Norte (Vila Estrutural)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (24 , 'Setor Leste (Vila Estrutural)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (25 , 'Setor Especial (Vila Estrutural)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (26 , 'Vila Estrutural', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (27 , 'Área Rural da Vila Estrutural', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (28 , 'Setor de Mansões do Lago Norte', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (29 , 'Setor de Habitações Individuais Norte', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (30 , 'Varjão', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (31 , 'Setor Habitacional Taquari (Lago Norte)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (32 , 'Setor de Postos e Motéis Norte (Lago Norte)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (33 , 'Área Rural do Lago Norte', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (34 , 'Paranoá', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (35 , 'Paranoá Parque (Paranoá)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (36 , 'Área Rural do Paranoá', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (37 , 'Itapoã I', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (38 , 'Itapoã II', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (39 , 'Del Lago I (Itapoã)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (40 , 'Del Lago II (Itapoã)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (41 , 'Fazendinha (Itapoã)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (42 , 'Setor de Mansões Dom Bosco (Lago Sul)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (43 , 'Setor de Habitações Individuais Sul', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (44 , 'Setor Habitacional Jardim Botânico', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (45 , 'Centro (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (46 , 'Bora Manso', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (47 , 'Morro Azul (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (48 , 'Setor Tradicional (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (49 , 'Setor Residencial Oeste (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (50 , 'Vila Nova (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (51 , 'João Cândido (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (52 , 'São Gabriel (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (53 , 'São Francisco (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (54 , 'Quinta dos Ipês (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (55 , 'Residencial Morro da Cruz (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (56 , 'Residencial Vitória (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (57 , 'Vila São José (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (58 , 'Residencial do Bosque (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (59 , 'Bela Vista (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (60 , 'São Bartolomeu (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (61 , 'Vila do Boa (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (62 , 'Residencial Itaipu (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (63 , 'Bonsucesso (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (64 , 'Jardins Mangueiral (São Sebastião)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (65 , 'Área Rural de São Sebastião', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (66 , 'Núcleo Bandeirante', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (67 , 'Candangolândia', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (68 , 'Metropolitana (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (69 , 'Vila Cauhy (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (70 , 'Setor Placa da Mercedes (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (71 , 'Área de Desenvolvimento Econômico (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (72 , 'Setor de Indústrias Bernardo Sayão (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (73 , 'Setor de Áreas Isoladas Sul (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (74 , 'Setor de Postos e Motéis Sul (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (75 , 'Setor Juscelino Kubitschek (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (76 , 'Park Way', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (77 , 'Núcleo Rural Vargem Bonita (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (78 , 'Setor de Chácaras Córrego da Onça (Núcleo Bandeirante)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (79 , 'Riacho Fundo I', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (80 , 'Riacho Fundo II', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (81 , 'Norte (Águas Claras)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (82 , 'Sul (Águas Claras)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (83 , 'Areal (Águas Claras)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (84 , 'Área de Desenvolvimento Econômico (Águas Claras)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (85 , 'Setor Habitacional Vereda Grande (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (86 , 'Setor Habitacional Arniqueira (Águas Claras)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (87 , 'Setor Habitacional Samambaia (Vicente Pires)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (88 , 'Vila São José (Vicente Pires)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (89 , 'Taguatinga Centro (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (90 , 'Taguatinga Sul (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (91 , 'Setor Habitacional Vicente Pires', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (92 , 'Setor Industrial (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (93 , 'Setor de Desenvolvimento Econômico (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (94 , 'Taguatinga Norte (Taguatinga)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (95 , 'Área Rural de Taguatinga', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (96 , 'Ceilândia Sul (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (97 , 'Ceilândia Norte (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (98 , 'Ceilândia Centro (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (99 , 'Ceilândia Centro (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (100, 'Ceilândia Sul (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (101, 'Área de Desenvolvimento Econômico (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (102, 'Setor Habitacional Pôr do Sol (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (103, 'Setor Habitacional Sol Nascente (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (104, 'Setor Industrial (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (105, 'Setor de Materiais de Construção (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (106, 'Ceilândia Norte (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (107, 'Condomínio Privê Lucena Roriz (Ceilândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (108, 'Área Rural de Ceilândia', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (109, 'Samambaia Sul (Samambaia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (110, 'Samambaia Norte (Samambaia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (111, 'Área Rural de Samambaia', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (112, 'Setor Central (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (113, 'Setor Sul (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (114, 'Setor Oeste (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (115, 'Ponte Alta Norte (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (116, 'Setor Norte (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (117, 'Gama', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (118, 'Setor Industrial (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (119, 'Setor Leste (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (120, 'Cidade Nova (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (121, 'Engenho das Lages (Gama)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (122, 'Área Rural do Gama', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (123, 'Santa Maria', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (124, 'Setor Habitacional Ribeirão (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (125, 'Núcleo Rural Alagados (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (126, 'Núcleo Rural Hortigranjeiro de Santa Maria', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (127, 'Condomínio Chácaras Ana Maria (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (128, 'Mansões Abraão I (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (129, 'Mansões Abraão II (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (130, 'Condomínio Residencial Santa Maria (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (131, 'Zona de Dinamização (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (132, 'Núcleo Rural Santa Maria', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (133, 'Setor Meireles (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (134, 'Área Alfa (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (135, 'Residencial Santos Dumont (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (136, 'Setor Habitacional Tororó (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (137, 'Condomínio Residencial Santa Mônica (Santa Maria)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (138, 'Área Rural de Santa Maria', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (139, 'Recanto das Emas', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (140, 'Área Rural do Recanto das Emas', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (141, 'Setor Norte (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (142, 'Setor Sul (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (143, 'Setor Tradicional (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (144, 'Veredas (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (145, 'Vila São José (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (146, 'Incra 8 (Brazlândia)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (147, 'Brazlândia', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (148, 'Área Rural de Brazlândia', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (149, 'Nova Colina (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (150, 'Setor Industrial (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (151, 'Setor Econômico de Sobradinho (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (152, 'Setor Oeste (Sobradinho II)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (153, 'Sobradinho', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (154, 'Setor de Mansões de Sobradinho', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (155, 'Serra Azul (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (156, 'Condomínio Mansões Sobradinho (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (157, 'Condomínio Comercial e Residencial Sobradinho (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (158, 'Vale das Acácias (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (159, 'Condomínio Mirante da Serra (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (160, 'Vila Rabelo I (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (161, 'Vila Rabelo II (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (162, 'Condomínio Vale dos Pinheiros (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (163, 'Setor Habitacional Contagem (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (164, 'Núcleo Rural Lago Oeste (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (165, 'Grande Colorado (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (166, 'Alto da Boa Vista (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (167, 'Estâncias Vila Rica (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (168, 'Setor Habitacional Fercal (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (169, 'Condomínio Império dos Nobres (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (170, 'Região dos Lagos (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (171, 'Nova Colina (Sobradinho)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (172, 'Área Rural de Sobradinho', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (173, 'Setor Hospitalar (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (174, 'Setor Administrativo (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (175, 'Setor de Educação (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (176, 'Setor de Hotéis e Diversões (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (177, 'Setor Comercial Central (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (178, 'Setor Recreativo e Cultural (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (179, 'Setor Norte (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (180, 'Setor Hospitalar (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (181, 'Setor Administrativo (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (182, 'Setor de Hotéis e Diversões (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (183, 'Vila Vicentina (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (184, 'Setor Sul (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (185, 'Setor Tradicional (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (186, 'Setor Norte (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (187, 'Jardim Roriz (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (188, 'Vila Nossa Senhora de Fátima (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (189, 'Setor Residencial Oeste (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (190, 'Área Universitária (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (191, 'Setor Residencial Norte (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (192, 'Setor Residencial Leste (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (193, 'Nossa Senhora de Fátima (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (194, 'Condomínio Guirra (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (195, 'Veneza II (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (196, 'Veneza I (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (197, 'Vila Dimas (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (198, 'Residencial São Francisco II (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (199, 'Residencial São Francisco I (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (200, 'San Sebastian (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (201, 'Recanto Feliz (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (202, 'Residencial Sandray (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (203, 'Portal do Amanhecer I (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (204, 'Vila Feliz (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (205, 'Residencial Flamboyant (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (206, 'Veneza III (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (207, 'Condomínio Prado (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (208, 'Portal do Amanhecer V (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (209, 'Condomínio Nova Esperança (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (210, 'Portal do Amanhecer V (Privê - Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (211, 'Portal do Amanhecer III (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (212, 'Fazenda Mestre D''Armas (Etapa II - Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (213, 'Quintas do Amanhecer III (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (214, 'Arapoanga (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (215, 'Residencial Condomínio Marissol (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (216, 'Condomínio Residencial Morada Nobre (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (217, 'Vale do Sol (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (218, 'Quintas do Amanhecer II (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (219, 'Fazenda Mestre D''Armas (Etapa III - Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (220, 'Portal do Amanhecer (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (221, 'Mansões do Amanhecer (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (222, 'Fazenda Mestre D''Armas (Etapa I - Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (223, 'Setor Residencial Mestre D''Armas (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (224, 'Vale do Amanhecer (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (225, 'Taquara (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (226, 'Residencial Cachoeira (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (227, 'Condomínio Nosso Lar (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (228, 'Residencial Samauma (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (229, 'Residencial Bica do DER (Gleba B - Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (230, 'Planaltina', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (231, 'Residencial Nova Planaltina (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (232, 'Estância Mestre D''Armas I (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (233, 'Residencial Sarandy (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (234, 'Estância Planaltina (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (235, 'Estância Mestre D''Armas IV (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (236, 'Estância Mestre D''Armas III (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (237, 'Estância Mestre D''Armas II (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (238, 'Estância Mestre D''Armas V (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (239, 'Recanto do Sossego (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (240, 'Estância Mestre D''Armas VI (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (241, 'Residencial Nova Esperança (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (242, 'Setor de Mansões Mestre D''Armas (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (243, 'Condomínio Parque Mônaco II (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (244, 'Condomínio Parque Mônaco (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (245, 'Condomínio Santa Mônica (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (246, 'Setor Mansões Itiquira (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (247, 'Condomínio Mestre D''Armas (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (248, 'Condomínio Coohaplan - Itiquira (Planaltina)', true, current_timestamp, current_timestamp, 1);
INSERT INTO public."NovoBairro" ("ID", nome, ativo, "createdAt", "updatedAt", "novaCidadeID") VALUES (249, 'Área Rural de Planaltina', true, current_timestamp, current_timestamp, 1);