//Enum para o metodo de pagameto

var PaymentMethodEnum = {
  VISA: 1,
  MASTERCARD: 2,
  BANK_SLIP: 10,
  AMERICAN_EXPRESS : 37,
  AURA : 45,
  DINERS : 55,
  HIPERCARD : 56,
  BB_ONLINE_TRANSFER : 58,
  BRADESCO_ONLINE_TRANSFER : 59,
  ITAU_ONLINE_TRANSFER : 60,
  BANRISUL_ONLINE_TRANSFER : 61,
  HSBC_ONLINE_TRANSFER : 62,
  ELO : 63
};